/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Profigure.gltf
*/

import {useGLTF} from "@react-three/drei";
import {forwardRef, useEffect} from "react";
import {useModel} from "../../../context/ModelContext";

const Profigure = forwardRef(function Profigure(
  {onMeshesFound, material, ...props},
  ref
) {
  const {scene, nodes} = useGLTF("/models/Profigure.gltf");
  const {setModelData} = useModel();

  useEffect(() => {
    setModelData({nodes});
  }, [nodes]);

  useEffect(() => {
    if (material && scene) {
      scene.traverse((child) => {
        if (child.isMesh) {
          child.material = material;
        }
      });
    }
  }, [material, scene]);

  return <primitive ref={ref} object={scene} {...props} />;
});

Profigure.displayName = "Profigure";
export default Profigure;

useGLTF.preload("/models/Profigure.gltf");
